import { Play } from '../types'

export async function exportPlayToPDF(
  canvasEl: HTMLCanvasElement,
  play: Play
): Promise<void> {
  const { jsPDF } = await import('jspdf')

  const imgData = canvasEl.toDataURL('image/png', 1.0)
  const canvasW = canvasEl.width
  const canvasH = canvasEl.height

  // Landscape A4
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()

  // Dark background
  pdf.setFillColor(10, 12, 15)
  pdf.rect(0, 0, pageW, pageH, 'F')

  // Header bar
  pdf.setFillColor(17, 20, 24)
  pdf.rect(0, 0, pageW, 18, 'F')

  // Title
  pdf.setTextColor(232, 255, 71)
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('PLAYBOOK PROTO', 10, 11)

  // Play name
  pdf.setTextColor(240, 244, 248)
  pdf.setFontSize(11)
  pdf.text(play.name.toUpperCase(), pageW / 2, 11, { align: 'center' })

  // Date
  pdf.setTextColor(138, 154, 176)
  pdf.setFontSize(8)
  pdf.setFont('helvetica', 'normal')
  const date = new Date(play.createdAt).toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric'
  })
  pdf.text(date, pageW - 10, 11, { align: 'right' })

  // Field image
  const margin = 10
  const top = 22
  const availW = pageW - margin * 2
  const availH = pageH - top - margin
  const ratio = canvasW / canvasH
  let imgW = availW
  let imgH = imgW / ratio
  if (imgH > availH) {
    imgH = availH
    imgW = imgH * ratio
  }
  const imgX = (pageW - imgW) / 2
  pdf.addImage(imgData, 'PNG', imgX, top, imgW, imgH)

  // Footer
  pdf.setTextColor(74, 85, 104)
  pdf.setFontSize(7)
  pdf.text('Generated by Playbook Proto — FieldIQ', pageW / 2, pageH - 4, { align: 'center' })

  pdf.save(`${play.name.replace(/\s+/g, '_')}.pdf`)
}
